### PR TITLE
add generation of jupyter book

### PR DESCRIPTION
**Pull request by annefou**
TO Do by maintainers (I don't have the rights to change the settings):
- In settings --> Actions --> General --> Workflow permissions:  enable **Read and write permissions** 
- once merged, Settings --> Pages: Deploy from gh-pages branch

### CODE REVIEW

**Comment by clausmichele** [comment]
The GitHub action is running at the moment!

**Comment by annefou** [comment]
> The GitHub action is running at the moment!

Cool! yes, `gh-pages` branch is there now: https://github.com/EO-College/cubes-and-clouds/tree/gh-pages 
I am not sure GitHub Pages site is configured yet. I do not see the rendered version https://eo-college.github.io/cubes-and-clouds/

**Comment by clausmichele** [comment]
Now it's is available

**Comment by annefou** [comment]
Ok. But it seems to be linked to the `main` branch and not `gh-pages`.

**Comment by clausmichele** [comment]
True, fixed now

**Pull request merged**
